import "./globals.css";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ToastProvider from "@/providers/ToastProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  restaurant: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ToastProvider>
            {session?.user.role === "restaurant"
              ? props.restaurant
              : props.children}
          </ToastProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
