apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: giftnichakul/orders:latest
          ports:
            - containerPort: 8004
          env:
            - name: MONGO_URL
              value: mongodb+srv://admin:SajA7iAFs2rn8LBt@cluster0.pfytphq.mongodb.net/ICANQ?retryWrites=true&w=majority
            - name: ORDER_SERVICE_PORT
              value: "8004"
            - name: MQ_HOST
              value: rabbitmq
            - name: GRPC_HOST
              value: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
